inventory_dot_core/Models/RelHardwareEmployee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace inventory_dot_core.Models
{
    public partial class RelHardwareEmployee
    {
        public RelHardwareEmployee()
        {           
        }

        [Display(Name ="Код")]
        public int RelheId { get; set; }

        [Display(Name = "Сотрудник")]
        public int RelheEmployeeId { get; set; }

        [Display(Name = "Оборудование")]
        [ForeignKey("WealthHardware")]
        public int RelheWhardId { get; set; }

        [Display(Name = "Сотрудник")]
        public virtual Employees RelheEmployee { get; set; }

        [Display(Name = "Оборудование")]
        public virtual WealthHardware RelheWhard { get; set; }
        
    }
}

inventory_dot_core/Controllers/RelHardwareEmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using inventory_dot_core.Models;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Authorization;

namespace inventory_dot_core.Controllers
{
    [Authorize(Policy = "RefEditorsRole")]
    public class RelHardwareEmployeesController : Controller
    {
        private readonly InventoryContext _context;

        private static string _emp_filter;
        private static int _emp_page;
        private static string _emp_sortExpression;
        //private static int indexPageOpnCnt = 0;
        private static int _employee_id;

        public RelHardwareEmployeesController(InventoryContext context)
        {
            _context = context;
        }

        // GET: RelHardwareEmployees
        public async Task<IActionResult> Index(int employee_id, string filter = "", int page = 1, string sortExpression = "RelheId",
            string emp_filter = "", int emp_page = 1, string emp_sortExpression = "EmployeeId")
        {
            ViewBag.Filter = filter;
            ViewBag.Page = page;
            ViewBag.SortExpression = sortExpression;
            ViewBag.EmployeeId = employee_id;

            // Открыли страницу от другого сотрудника - сохраняем параметры для перехода к сотрудникам
            if (_employee_id != employee_id)
            {
                _employee_id = employee_id;
                _emp_filter = emp_filter;
                _emp_page = emp_page;
                _emp_sortExpression = emp_sortExpression;
            }

            ViewBag.EmpFilter = _emp_filter;
            ViewBag.EmpPage = _emp_page;
            ViewBag.EmpSortExpression = _emp_sortExpression;

            var inventoryContext = _context.RelHardwareEmployee
                .Include(r => r.RelheEmployee)
                .Include(r => r.RelheWhard)
                .Where(e => e.RelheEmployeeId == employee_id)
                .AsQueryable();

            var _employee = _context.Employees.Find(employee_id);

            ViewBag.EmployeeName = _employee.EmployeeFullFio;

            int pageSize = 5;

            if (!string.IsNullOrWhiteSpace(filter))
            {
                filter = filter.ToUpper();
                inventoryContext = inventoryContext.Where(
                    e => EF.Functions.Like(e.RelheWhard.WhardName.ToUpper(), "%" + filter + "%")
                );
            }
            var model = await inventory_dot_core.Classes.Paging.PagingList.CreateAsync
                (
                   inventoryContext, pageSize, page, sortExpression, "RelheId"
                   );

            model.RouteValue = new RouteValueDictionary {
                { "filter", filter},
                {"page", page },
                {"sortExpression",sortExpression },
                {"employee_id",employee_id }
            };

            return View(model);
        }

        // GET: RelHardwareEmployees/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var relHardwareEmployee = await _context.RelHardwareEmployee
                .Include(r => r.RelheEmployee)
                .Include(r => r.RelheWhard)
                .FirstOrDefaultAsync(m => m.RelheId == id);
            if (relHardwareEmployee == null)
            {
                return NotFound();
            }

            return View(relHardwareEmployee);
        }

        // GET: RelHardwareEmployees/Create
        public IActionResult Create(int employee_id, string filter = "", int page = 1, string sortExpression = "RelheId")
        {
            ViewBag.Filter = filter;
            ViewBag.Page = page;
            ViewBag.SortExpression = sortExpression;
            ViewBag.EmployeeId = employee_id;

            var _employee = _context.Employees
                .Include(o => o.EmployeeOffice)
                .Where(e => e.EmployeeId == employee_id)
                .FirstOrDefault();

            ViewBag.EmployeeName = _employee.EmployeeFullFio;
            ViewBag.EmployeeRegionId = _employee.EmployeeRegionId;
            ViewBag.EmployeeOfficeId = _employee.EmployeeOfficeId;


            ViewData["RelheEmployeeId"] = new SelectList(_context.Employees, "EmployeeId", "EmployeeFirstname")
                .Where(e => e.Value == employee_id.ToString());
            ViewData["RelheWhardId"] = this.GetNotUseHardList(0, _employee.EmployeeRegionId, _employee.EmployeeOfficeId);
            return View();
        }

        // POST: RelHardwareEmployees/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RelheId,RelheEmployeeId,RelheWhardId")] RelHardwareEmployee relHardwareEmployee,
            int employee_id, string filter = "", int page = 1, string sortExpression = "RelheId")
        {
            ViewBag.Filter = filter;
            ViewBag.Page = page;
            ViewBag.SortExpression = sortExpression;


            var _employee = _context.Employees.Find(employee_id);

            ViewBag.EmployeeName = _employee.EmployeeFullFio;
            //ViewBag.EmployeeId = _employee.EmployeeId;

            relHardwareEmployee.RelheEmployeeId = employee_id;

            ModelState.Clear();


            if (ModelState.IsValid)
            {
                _context.Add(relHardwareEmployee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index),
                    new
                    {
                        employee_id,
                        filter,
                        page,
                        sortExpression
                    });
            }


            ViewData["RelheEmployeeId"] = new SelectList(_context.Employees, "EmployeeId", "EmployeeFullFio")
                .Where(e => e.Value == employee_id.ToString());
            ViewData["RelheWhardId"] = new SelectList(
                this.GetNotUseHardList(0, relHardwareEmployee.RelheEmployee.EmployeeRegionId, relHardwareEmployee.RelheEmployee.EmployeeOfficeId),
                "WhardId", "WhardName");

            return View(relHardwareEmployee);
        }

        // GET: RelHardwareEmployees/Edit/5
        public async Task<IActionResult> Edit(int? id, int employee_id, string filter = "", int page = 1, string sortExpression = "RelheId")
        {
            ViewBag.Filter = filter;
            ViewBag.Page = page;
            ViewBag.SortExpression = sortExpression;
            ViewBag.EmployeeId = employee_id;

            if (id == null)
            {
                return NotFound();
            }

            var relHardwareEmployee = await _context.RelHardwareEmployee.FindAsync(id);
            if (relHardwareEmployee == null)
            {
                return NotFound();
            }
            ViewData["RelheEmployeeId"] = new SelectList(_context.Employees, "EmployeeId", "EmployeeFirstname", relHardwareEmployee.RelheEmployeeId);
            ViewData["RelheWhardId"] = new SelectList(_context.WealthHardware, "WhardId", "WhardId", relHardwareEmployee.RelheWhardId);
            return View(relHardwareEmployee);
        }

        // POST: RelHardwareEmployees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RelheId,RelheEmployeeId,RelheWhardId")] RelHardwareEmployee relHardwareEmployee,
            int employee_id, string filter = "", int page = 1, string sortExpression = "RelheId")
        {
            ViewBag.Filter = filter;
            ViewBag.Page = page;
            ViewBag.SortExpression = sortExpression;
            ViewBag.EmployeeId = employee_id;

            if (id != relHardwareEmployee.RelheId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(relHardwareEmployee);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RelHardwareEmployeeExists(relHardwareEmployee.RelheId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["RelheEmployeeId"] = new SelectList(_context.Employees, "EmployeeId", "EmployeeFirstname", relHardwareEmployee.RelheEmployeeId);
            ViewData["RelheWhardId"] = new SelectList(_context.WealthHardware, "WhardId", "WhardId", relHardwareEmployee.RelheWhardId);
            return View(relHardwareEmployee);
        }

        // GET: RelHardwareEmployees/Delete/5
        public async Task<IActionResult> Delete(int? id, int employee_id, string filter = "", int page = 1, string sortExpression = "RelheId")
        {
            ViewBag.Filter = filter;
            ViewBag.Page = page;
            ViewBag.SortExpression = sortExpression;
            ViewBag.EmployeeId = employee_id;

            if (id == null)
            {
                return NotFound();
            }

            var relHardwareEmployee = await _context.RelHardwareEmployee
                .Include(r => r.RelheEmployee)
                .Include(r => r.RelheWhard)

inventory_dot_core/Views/RelHardwareEmployees/Create.cshtml
@model inventory_dot_core.Models.RelHardwareEmployee

@{
    ViewData["Title"] = $"Добавление оборудавания на РМ сотрудника: {ViewBag.EmployeeName}";
}

<h1>Добавление оборудования</h1>

<h4>На РМ сотрудника: @ViewBag.EmployeeName</h4>
<hr />

<input hidden id="eRegionId" value="@ViewBag.EmployeeRegionId" />
<input hidden id="eOfficeId" value="@ViewBag.EmployeeOfficeId" />


<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RelheWhardId" class="control-label"></label>
                <input hidden id="whardSearchId" name="whardSeach" class="form-control" />
                <select asp-for="RelheWhardId"
                        class="chosen-select"
                        asp-items="ViewBag.RelheWhardId"
                        style="font-family:Arial !important;"></select>
            </div>
            <div class="form-group">
                <input type="submit"
                       value="Сохранить"
                       class="btn btn-mdb-color btn-sm"
                       method="post"
                       asp-route-employee_id="@ViewBag.EmployeeId"
                       asp-route-filter="@ViewBag.Filter"
                       asp-route-sortExpression="@ViewBag.SortExpression"
                       asp-route-page="@ViewBag.Page" /> |
                <a class="btn btn-mdb-color btn-sm" asp-action="Index"
                   asp-route-employee_id="@ViewBag.EmployeeId"
                   asp-route-filter="@ViewBag.Filter"
                   asp-route-sortExpression="@ViewBag.SortExpression"
                   asp-route-page="@ViewBag.Page">
                    Назад
                </a>
            </div>
        </form>
    </div>
</div>

<script type="text/javascript">
    $('#RelheWhardId').chosen({ width: '100%' });    
</script>
<script src="~/js/scripts/emp_workplace.js"></script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

inventory_dot_core/Views/RelHardwareEmployees/Delete.cshtml
@model inventory_dot_core.Models.RelHardwareEmployee
@using inventory_dot_core.Classes

@{
    ViewData["Title"] = $"{Dictionary.frasesDictionary["Delete"]} оборудование {Model.RelheWhard.WhardName}";
}

<h1>@Dictionary.frasesDictionary["Delete"]</h1>

<h3>@Dictionary.frasesDictionary["DeleteConfirm"]</h3>
<div>
    <h4>Удаление оборудования с РМ сотрудника</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RelheEmployee)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RelheEmployee.EmployeeFullFio)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RelheWhard)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RelheWhard.WhardName)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="RelheId" />
        <input type="submit" value="Удалить" class="btn btn-danger btn-sm"
               formmethod="post"
               asp-route-filter="@ViewBag.Filter"
               asp-route-sortExpression="@ViewBag.SortExpression"
               asp-route-page="@ViewBag.Page"
               asp-route-employee_id="@ViewBag.EmployeeId"/> |
        <a class="btn btn-mdb-color btn-sm" asp-action="Index"
           asp-route-filter="@ViewBag.Filter"
           asp-route-sortExpression="@ViewBag.SortExpression"
           asp-route-page="@ViewBag.Page"
           asp-route-employee_id="@ViewBag.EmployeeId">
            Назад
        </a>
    </form>
</div>

inventory_dot_core/Views/RelHardwareEmployees/Details.cshtml
@model inventory_dot_core.Models.RelHardwareEmployee

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>RelHardwareEmployee</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RelheEmployee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RelheEmployee.EmployeeFirstname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RelheWhard)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RelheWhard.WhardId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.RelheId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

inventory_dot_core/Views/RelHardwareEmployees/Edit.cshtml
@model inventory_dot_core.Models.RelHardwareEmployee

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>RelHardwareEmployee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="RelheId" />
            <div class="form-group">
                <label asp-for="RelheEmployeeId" class="control-label"></label>
                <select asp-for="RelheEmployeeId" class="form-control" asp-items="ViewBag.RelheEmployeeId"></select>
                <span asp-validation-for="RelheEmployeeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RelheWhardId" class="control-label"></label>
                <select asp-for="RelheWhardId" class="form-control" asp-items="ViewBag.RelheWhardId"></select>
                <span asp-validation-for="RelheWhardId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

inventory_dot_core/Views/RelHardwareEmployees/Index.cshtml
@model inventory_dot_core.Classes.Paging.PagingList<inventory_dot_core.Models.RelHardwareEmployee>
@using inventory_dot_core.Classes;

@{
    ViewData["Title"] = $"Рабочее место сотрудника: {ViewBag.EmployeeName}";
}

<h1>Рабочее место сотрудника: @ViewBag.EmployeeName</h1>

<p>
    <a asp-action="Create" class="btn btn-mdb-color btn-sm"
       asp-route-employee_id="@ViewBag.EmployeeId"
       asp-route-page="@Model.PageIndex"
       asp-route-filter="@ViewBag.Filter"
       asp-route-sortExpression="@ViewBag.SortExpression">
        Добавить оборудование
    </a> |
    <a class="btn btn-mdb-color btn-sm"
       asp-controller="Employees"
       asp-action="Index"
       asp-route-filter="@ViewBag.EmpFilter"
       asp-route-sortExpression="@ViewBag.EmpSortExpression"
       asp-route-page="@ViewBag.EmpPage">
        Назад
    </a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RelheWhard.WhardInumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RelheWhard.WhardName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.RelheWhard.WhardInumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RelheWhard.WhardName)
                </td>
                <td>                    
                    <a asp-action="Delete" class="btn btn-mdb-color btn-sm"
                       asp-route-employee_id="@ViewBag.EmployeeId"
                       asp-route-id="@item.RelheId"
                       asp-route-page="@Model.PageIndex"
                       asp-route-filter="@ViewBag.Filter"
                       asp-route-sortExpression="@ViewBag.SortExpression">@Dictionary.frasesDictionary["Delete"]</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<nav>
    <partial name="_PagerPartial" />
</nav>

inventory_dot_core/Views/RelHardwareEmployees/Report.cshtml
@{
    ViewData["Title"] = "Report";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Report</h1>

inventory_dot_core/Views/RelHardwareEmployees/_hardWareModalFrm.cshtml
@model inventory_dot_core.Classes.Paging.PagingList<inventory_dot_core.Models.WealthSoftware>

@using (Html.BeginForm("Contact", "RelHardwareEmployees"))
{
    <div class="modal fade" id="add-contact" tabindex="-1" role="dialog" aria-labelledby="addContactLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="addContactLabel">Add contact</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>                    
                </div>
                <hr />
                <div class="modal-body">
                    <nav class="navbar navbar-expand-md navbar-light bg-light">
                        <partial name="_FilterPartial" />
                    </nav>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.WsoftName)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.WsoftInumber)
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.WsoftName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.WsoftInumber)
                                </td>
                                <td></td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <hr />
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save</button>
                </div>
            </div>
        </div>
    </div>
    <script src="~/js/scripts/modal.js"></script>
}